[build]
base = "/"
publish = "public"
command = "npm run build"

[build.environment]
NODE_ENV = "production"

[functions]
directory = "netlify/functions/"

[[plugins]]
package = "@netlify/plugin-gatsby"
