on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix run .#docker-manifest --impure
        env:
          GH_TOKEN: ${{ github.token }}
