on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v5
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: nix run .#dockerManifest --impure --log-lines 1000
